// Comprehensive list of countries
export const COUNTRIES = [
  { value: 'us', label: 'United States' },
  { value: 'ca', label: 'Canada' },
  { value: 'gb', label: 'United Kingdom' },
  { value: 'au', label: 'Australia' },
  { value: 'de', label: 'Germany' },
  { value: 'fr', label: 'France' },
  { value: 'it', label: 'Italy' },
  { value: 'es', label: 'Spain' },
  { value: 'nl', label: 'Netherlands' },
  { value: 'be', label: 'Belgium' },
  { value: 'ch', label: 'Switzerland' },
  { value: 'at', label: 'Austria' },
  { value: 'se', label: 'Sweden' },
  { value: 'no', label: 'Norway' },
  { value: 'dk', label: 'Denmark' },
  { value: 'fi', label: 'Finland' },
  { value: 'pl', label: 'Poland' },
  { value: 'ie', label: 'Ireland' },
  { value: 'pt', label: 'Portugal' },
  { value: 'gr', label: 'Greece' },
  { value: 'cz', label: 'Czech Republic' },
  { value: 'hu', label: 'Hungary' },
  { value: 'ro', label: 'Romania' },
  { value: 'bg', label: 'Bulgaria' },
  { value: 'hr', label: 'Croatia' },
  { value: 'sk', label: 'Slovakia' },
  { value: 'si', label: 'Slovenia' },
  { value: 'ee', label: 'Estonia' },
  { value: 'lv', label: 'Latvia' },
  { value: 'lt', label: 'Lithuania' },
  { value: 'jp', label: 'Japan' },
  { value: 'cn', label: 'China' },
  { value: 'kr', label: 'South Korea' },
  { value: 'in', label: 'India' },
  { value: 'sg', label: 'Singapore' },
  { value: 'my', label: 'Malaysia' },
  { value: 'th', label: 'Thailand' },
  { value: 'ph', label: 'Philippines' },
  { value: 'id', label: 'Indonesia' },
  { value: 'vn', label: 'Vietnam' },
  { value: 'tw', label: 'Taiwan' },
  { value: 'hk', label: 'Hong Kong' },
  { value: 'nz', label: 'New Zealand' },
  { value: 'za', label: 'South Africa' },
  { value: 'ae', label: 'United Arab Emirates' },
  { value: 'sa', label: 'Saudi Arabia' },
  { value: 'il', label: 'Israel' },
  { value: 'tr', label: 'Turkey' },
  { value: 'eg', label: 'Egypt' },
  { value: 'ng', label: 'Nigeria' },
  { value: 'ke', label: 'Kenya' },
  { value: 'mx', label: 'Mexico' },
  { value: 'br', label: 'Brazil' },
  { value: 'ar', label: 'Argentina' },
  { value: 'cl', label: 'Chile' },
  { value: 'co', label: 'Colombia' },
  { value: 'pe', label: 'Peru' },
  { value: 've', label: 'Venezuela' },
  { value: 'bd', label: 'Bangladesh' },
  { value: 'pk', label: 'Pakistan' },
  { value: 'lk', label: 'Sri Lanka' },
  { value: 'np', label: 'Nepal' },
  { value: 'mm', label: 'Myanmar' },
  { value: 'kh', label: 'Cambodia' },
  { value: 'la', label: 'Laos' },
  { value: 'bn', label: 'Brunei' },
  { value: 'mo', label: 'Macau' },
  { value: 'ru', label: 'Russia' },
  { value: 'ua', label: 'Ukraine' },
  { value: 'by', label: 'Belarus' },
  { value: 'kz', label: 'Kazakhstan' },
  { value: 'uz', label: 'Uzbekistan' },
  { value: 'ge', label: 'Georgia' },
  { value: 'am', label: 'Armenia' },
  { value: 'az', label: 'Azerbaijan' },
]

