// Comprehensive list of industries with numeric IDs
export const INDUSTRIES = [
  { value: 1, label: 'Electronics' },
  { value: 2, label: 'Fashion & Apparel' },
  { value: 3, label: 'Home & Living' },
  { value: 4, label: 'Beauty & Personal Care' },
  { value: 5, label: 'Health & Wellness' },
  { value: 6, label: 'Sports & Outdoors' },
  { value: 7, label: 'Toys & Games' },
  { value: 8, label: 'Books & Media' },
  { value: 9, label: 'Automotive' },
  { value: 10, label: 'Food & Beverage' },
  { value: 11, label: 'Pet Supplies' },
  { value: 12, label: 'Office Supplies' },
  { value: 13, label: 'Jewelry & Accessories' },
  { value: 14, label: 'Furniture' },
  { value: 15, label: 'Kitchen & Dining' },
  { value: 16, label: 'Garden & Tools' },
  { value: 17, label: 'Baby Products' },
  { value: 18, label: 'Computers & Accessories' },
  { value: 19, label: 'Mobile Phones & Accessories' },
  { value: 20, label: 'Audio & Video' },
  { value: 21, label: 'Gaming' },
  { value: 22, label: 'Cameras & Photography' },
  { value: 23, label: 'Watches' },
  { value: 24, label: 'Luggage & Travel' },
  { value: 25, label: 'Musical Instruments' },
  { value: 26, label: 'Industrial & Scientific' },
  { value: 27, label: 'Software' },
  { value: 28, label: 'Arts & Crafts' },
  { value: 29, label: 'Collectibles' },
  { value: 30, label: 'Antiques' },
]

// Document types for business verification
export const DOCUMENT_TYPES = [
  { value: 'identity', label: 'Identity Document' },
  { value: 'passport', label: 'Passport' },
  { value: 'business_registration', label: 'Business Registration' },
  { value: 'tax_certificate', label: 'Tax Certificate' },
]
