// Comprehensive list of industries
export const INDUSTRIES = [
  { value: 'electronics', label: 'Electronics' },
  { value: 'fashion', label: 'Fashion & Apparel' },
  { value: 'home', label: 'Home & Living' },
  { value: 'beauty', label: 'Beauty & Personal Care' },
  { value: 'health', label: 'Health & Wellness' },
  { value: 'sports', label: 'Sports & Outdoors' },
  { value: 'toys', label: 'Toys & Games' },
  { value: 'books', label: 'Books & Media' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'food', label: 'Food & Beverage' },
  { value: 'pet', label: 'Pet Supplies' },
  { value: 'office', label: 'Office Supplies' },
  { value: 'jewelry', label: 'Jewelry & Accessories' },
  { value: 'furniture', label: 'Furniture' },
  { value: 'kitchen', label: 'Kitchen & Dining' },
  { value: 'garden', label: 'Garden & Tools' },
  { value: 'baby', label: 'Baby Products' },
  { value: 'computers', label: 'Computers & Accessories' },
  { value: 'phones', label: 'Mobile Phones & Accessories' },
  { value: 'audio', label: 'Audio & Video' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'cameras', label: 'Cameras & Photography' },
  { value: 'watches', label: 'Watches' },
  { value: 'luggage', label: 'Luggage & Travel' },
  { value: 'musical', label: 'Musical Instruments' },
  { value: 'industrial', label: 'Industrial & Scientific' },
  { value: 'software', label: 'Software' },
  { value: 'art', label: 'Arts & Crafts' },
  { value: 'collectibles', label: 'Collectibles' },
  { value: 'antiques', label: 'Antiques' },
]

